apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalization-agent
  namespace: aegis-orchestrator
  labels:
    app: personalization-agent
    component: personalization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personalization-agent
  template:
    metadata:
      labels:
        app: personalization-agent
        component: personalization
    spec:
      containers:
      - name: personalization-agent
        image: aegis-orchestrator/personalization-agent:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aegis-secrets
              key: GEMINI_API_KEY
        - name: GEMINI_MODEL
          valueFrom:
            secretKeyRef:
              name: aegis-secrets
              key: GEMINI_MODEL
        - name: MCP_SERVER_HOST
          value: "mcp-server"
        - name: MCP_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: aegis-config
              key: MCP_SERVER_PORT
        - name: A2A_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: aegis-config
              key: A2A_BROKER_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: aegis-config
              key: REDIS_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: aegis-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: personalization-agent
  namespace: aegis-orchestrator
  labels:
    app: personalization-agent
spec:
  selector:
    app: personalization-agent
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
